 <script src="{{ asset('homepage/vendor/jquery/jquery.min.js') }}"></script>
    <script src="{{ asset('homepage/vendor/popper.js/umd/popper.min.js') }}"> </script>
    <script src="{{ asset('homepage/vendor/bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('homepage/vendor/jquery.cookie/jquery.cookie.js') }}"> </script>
    <script src="{{ asset('homepage/vendor/waypoints/lib/jquery.waypoints.min.js') }}"> </script>
    <script src="{{ asset('homepage/vendor/jquery.counterup/jquery.counterup.min.js') }}"> </script>
    <script src="{{ asset('homepage/vendor/owl.carousel/owl.carousel.min.js') }}"></script>
    <script src="{{ asset('homepage/vendor/owl.carousel2.thumbs/owl.carousel2.thumbs.min.js') }}"></script>
    <script src="{{ asset('homepage/js/jquery.parallax-1.1.3.js') }}"></script>
    <script src="{{ asset('homepage/vendor/bootstrap-select/js/bootstrap-select.min.js') }}"></script>
    <script src="{{ asset('homepage/vendor/jquery.scrollto/jquery.scrollTo.min.js') }}"></script>
    <script src="{{ asset('homepage/js/front.js') }}"></script>
